### ISSUE TITLE
关于FU厂贴纸的问题

### ISSUE THREAD

**Issue by key3board** [ksvcmc/KMCFuFilter_iOS#2]
1.20 版本的 'KMCFuFilter’   /**

-(void)startShowingMaterial:(KMCArMaterial *)material;

只有激活的素材？  然后没有  类似-(void)stopMaterial() 接口吗？  用户不想带贴纸连美颜都不能用了吗？
demo里面只是把 filter  换成 KSYBeautifyProFilter 这个filter。  可是我想要的是 fu美颜的filter 啊？
请尽快解决啊

**Comment by jiangdsuccess** [comment]
已解决，https://github.com/ksvcmc/KMCFuFilter_iOS/releases/tag/v1.3.0
